/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'confirmed' : boolean,
  'scheduledAt' : Timestamp,
}
export type BeeError = { 'invalidState' : string } |
  { 'notAuthorized' : null } |
  { 'notFound' : null };
export type BeeId = bigint;
export interface BeeInput { 'name' : string, 'specialty' : string }
export interface BeeView {
  'id' : BeeId,
  'name' : string,
  'createdAt' : Timestamp,
  'specialty' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface DashboardStats {
  'reviewsCount' : bigint,
  'depositsCollected' : bigint,
  'newRequests' : bigint,
  'upcomingAppointments' : bigint,
  'activeJobs' : bigint,
}
export interface Deposit {
  'method' : PaymentMethod,
  'paid' : boolean,
  'stripeSessionId' : [] | [string],
  'amount' : bigint,
  'paidAt' : [] | [Timestamp],
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type JobError = { 'paymentError' : string } |
  { 'invalidState' : string } |
  { 'notAuthorized' : null } |
  { 'notFound' : null };
export type JobId = bigint;
export interface JobRequestInput {
  'customerName' : string,
  'preferredTiming' : string,
  'description' : string,
  'photoIds' : Array<PhotoId>,
  'ownParts' : boolean,
  'email' : string,
  'category' : ServiceCategory,
  'phone' : string,
  'packageInterest' : boolean,
}
export interface JobRequestView {
  'id' : JobId,
  'customerName' : string,
  'status' : JobStatus,
  'completedAt' : [] | [Timestamp],
  'review' : [] | [Review],
  'packageEnrollment' : [] | [PackageEnrollment],
  'preferredTiming' : string,
  'appointment' : [] | [Appointment],
  'createdAt' : Timestamp,
  'quote' : [] | [Quote],
  'description' : string,
  'photoIds' : Array<PhotoId>,
  'deposit' : [] | [Deposit],
  'ownParts' : boolean,
  'email' : string,
  'referenceCode' : ReferenceCode,
  'category' : ServiceCategory,
  'assignedBeeName' : [] | [string],
  'phone' : string,
  'assignedBeeId' : [] | [BeeId],
}
export type JobStatus = { 'scheduled' : null } |
  { 'requested' : null } |
  { 'completed' : null } |
  { 'quoted' : null } |
  { 'inProgress' : null };
export interface PackageEnrollment {
  'startedAt' : Timestamp,
  'active' : boolean,
  'monthlyPrice' : bigint,
  'includedVisits' : bigint,
}
export type PaymentMethod = { 'stripe' : null } |
  { 'cashApp' : null };
export type PhotoId = string;
export interface Quote {
  'discountApplied' : boolean,
  'discountAmount' : bigint,
  'note' : string,
  'sentAt' : Timestamp,
  'amount' : bigint,
}
export type ReferenceCode = string;
export type Result = { 'ok' : BeeView } |
  { 'err' : BeeError };
export type Result_1 = { 'ok' : JobRequestView } |
  { 'err' : JobError };
export type Result_2 = { 'ok' : JobRequestView } |
  { 'err' : BeeError };
export type Result_3 = { 'ok' : string } |
  { 'err' : JobError };
export type Result_4 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Review {
  'createdAt' : Timestamp,
  'comment' : string,
  'rating' : bigint,
}
export type ServiceCategory = { 'fixIt' : null } |
  { 'showMe' : null } |
  { 'house' : null } |
  { 'cleanOrganize' : null } |
  { 'mowing' : null } |
  { 'errands' : null } |
  { 'moveLift' : null } |
  { 'yardPlants' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface VisitRecord {
  'service' : ServiceCategory,
  'completedAt' : Timestamp,
  'jobId' : JobId,
  'referenceCode' : ReferenceCode,
  'beeName' : [] | [string],
  'beeId' : [] | [BeeId],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_4>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Guest: accept the quote attached to a job request.
   */
  'acceptQuote' : ActorMethod<[ReferenceCode], Result_1>,
  /**
   * / Admin: advance a job request to its next lifecycle status.
   */
  'advanceStatus' : ActorMethod<[JobId], Result_1>,
  /**
   * / Admin: assign a bee to a job request.
   */
  'assignBeeToJob' : ActorMethod<[JobId, BeeId], Result_2>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Guest: confirm the scheduled appointment.
   */
  'confirmAppointment' : ActorMethod<[ReferenceCode], Result_1>,
  /**
   * / Guest: confirm a Stripe deposit payment and mark the deposit paid.
   */
  'confirmDepositPayment' : ActorMethod<[ReferenceCode], Result_1>,
  /**
   * / Admin: create a bee (employee) with a name and specialty.
   */
  'createBee' : ActorMethod<[BeeInput], Result>,
  /**
   * / Guest: create a Stripe checkout session for a set of shopping items.
   */
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  /**
   * / Guest: create a Stripe checkout session for the 50% deposit on an accepted quote.
   */
  'createDepositCheckoutSession' : ActorMethod<
    [ReferenceCode, string, string],
    Result_3
  >,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Return the backend's behavioral API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Admin: read the newest-first visit history for a job request's customer.
   */
  'getCustomerVisitHistory' : ActorMethod<[JobId], Array<VisitRecord>>,
  /**
   * / Admin: read dashboard statistics.
   */
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  /**
   * / Admin: fetch a single job request by id.
   */
  'getRequest' : ActorMethod<[JobId], [] | [JobRequestView]>,
  /**
   * / Guest: fetch a job request by its public reference code.
   */
  'getRequestByReference' : ActorMethod<[ReferenceCode], [] | [JobRequestView]>,
  /**
   * / Guest: read the status of a Stripe checkout session.
   */
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  /**
   * / Guest: read the newest-first visit history for a reference code.
   */
  'getVisitHistory' : ActorMethod<[ReferenceCode], Array<VisitRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Whether Stripe checkout is configured for deposit payments.
   */
  'isStripeConfigured' : ActorMethod<[], boolean>,
  /**
   * / Admin: list all bees.
   */
  'listBees' : ActorMethod<[], Array<BeeView>>,
  /**
   * / Admin: list all job requests.
   */
  'listRequests' : ActorMethod<[], Array<JobRequestView>>,
  /**
   * / Guest: record a deposit payment for an accepted quote.
   */
  'recordDeposit' : ActorMethod<[ReferenceCode, PaymentMethod], Result_1>,
  /**
   * / Admin: schedule an appointment for a job request. Notifies BOTH the
   * / customer and the owner.
   */
  'scheduleAppointment' : ActorMethod<[JobId, Timestamp], Result_1>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Admin: mark a job request's customer as being on the monthly package.
   */
  'setPackageEnrollment' : ActorMethod<[JobId, boolean], Result_2>,
  /**
   * / Admin: set the quote amount and note for a job request. When the customer
   * / indicated they supply their own parts, a 10% discount is applied and
   * / recorded on the quote.
   */
  'setQuote' : ActorMethod<[JobId, bigint, string], Result_1>,
  /**
   * / Admin: store the Stripe secret key and allowed countries.
   */
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  /**
   * / Guest: submit a new job request and receive its public reference code.
   */
  'submitRequest' : ActorMethod<[JobRequestInput], ReferenceCode>,
  /**
   * / Guest: submit a review for a completed job.
   */
  'submitReview' : ActorMethod<[ReferenceCode, bigint, string], Result_1>,
  /**
   * / HTTP outcall transform required by the Stripe client.
   */
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  /**
   * / Admin: update a bee's name and specialty.
   */
  'updateBee' : ActorMethod<[BeeId, BeeInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];