/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ReferenceCode = IDL.Text;
export const JobId = IDL.Nat;
export const JobStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'requested' : IDL.Null,
  'completed' : IDL.Null,
  'quoted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Review = IDL.Record({
  'createdAt' : Timestamp,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const PackageEnrollment = IDL.Record({
  'startedAt' : Timestamp,
  'active' : IDL.Bool,
  'monthlyPrice' : IDL.Nat,
  'includedVisits' : IDL.Nat,
});
export const Appointment = IDL.Record({
  'confirmed' : IDL.Bool,
  'scheduledAt' : Timestamp,
});
export const Quote = IDL.Record({
  'discountApplied' : IDL.Bool,
  'discountAmount' : IDL.Nat,
  'note' : IDL.Text,
  'sentAt' : Timestamp,
  'amount' : IDL.Nat,
});
export const PhotoId = IDL.Text;
export const PaymentMethod = IDL.Variant({
  'stripe' : IDL.Null,
  'cashApp' : IDL.Null,
});
export const Deposit = IDL.Record({
  'method' : PaymentMethod,
  'paid' : IDL.Bool,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'paidAt' : IDL.Opt(Timestamp),
});
export const ServiceCategory = IDL.Variant({
  'fixIt' : IDL.Null,
  'showMe' : IDL.Null,
  'house' : IDL.Null,
  'cleanOrganize' : IDL.Null,
  'mowing' : IDL.Null,
  'errands' : IDL.Null,
  'moveLift' : IDL.Null,
  'yardPlants' : IDL.Null,
});
export const BeeId = IDL.Nat;
export const JobRequestView = IDL.Record({
  'id' : JobId,
  'customerName' : IDL.Text,
  'status' : JobStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'review' : IDL.Opt(Review),
  'packageEnrollment' : IDL.Opt(PackageEnrollment),
  'preferredTiming' : IDL.Text,
  'appointment' : IDL.Opt(Appointment),
  'createdAt' : Timestamp,
  'quote' : IDL.Opt(Quote),
  'description' : IDL.Text,
  'photoIds' : IDL.Vec(PhotoId),
  'deposit' : IDL.Opt(Deposit),
  'ownParts' : IDL.Bool,
  'email' : IDL.Text,
  'referenceCode' : ReferenceCode,
  'category' : ServiceCategory,
  'assignedBeeName' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'assignedBeeId' : IDL.Opt(BeeId),
});
export const JobError = IDL.Variant({
  'paymentError' : IDL.Text,
  'invalidState' : IDL.Text,
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Null,
});
export const Result_1 = IDL.Variant({
  'ok' : JobRequestView,
  'err' : JobError,
});
export const BeeError = IDL.Variant({
  'invalidState' : IDL.Text,
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Null,
});
export const Result_2 = IDL.Variant({
  'ok' : JobRequestView,
  'err' : BeeError,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BeeInput = IDL.Record({
  'name' : IDL.Text,
  'specialty' : IDL.Text,
});
export const BeeView = IDL.Record({
  'id' : BeeId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'specialty' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : BeeView, 'err' : BeeError });
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : JobError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const VisitRecord = IDL.Record({
  'service' : ServiceCategory,
  'completedAt' : Timestamp,
  'jobId' : JobId,
  'referenceCode' : ReferenceCode,
  'beeName' : IDL.Opt(IDL.Text),
  'beeId' : IDL.Opt(BeeId),
});
export const DashboardStats = IDL.Record({
  'reviewsCount' : IDL.Nat,
  'depositsCollected' : IDL.Nat,
  'newRequests' : IDL.Nat,
  'upcomingAppointments' : IDL.Nat,
  'activeJobs' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const JobRequestInput = IDL.Record({
  'customerName' : IDL.Text,
  'preferredTiming' : IDL.Text,
  'description' : IDL.Text,
  'photoIds' : IDL.Vec(PhotoId),
  'ownParts' : IDL.Bool,
  'email' : IDL.Text,
  'category' : ServiceCategory,
  'phone' : IDL.Text,
  'packageInterest' : IDL.Bool,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_4], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'acceptQuote' : IDL.Func([ReferenceCode], [Result_1], []),
  'advanceStatus' : IDL.Func([JobId], [Result_1], []),
  'assignBeeToJob' : IDL.Func([JobId, BeeId], [Result_2], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmAppointment' : IDL.Func([ReferenceCode], [Result_1], []),
  'confirmDepositPayment' : IDL.Func([ReferenceCode], [Result_1], []),
  'createBee' : IDL.Func([BeeInput], [Result], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDepositCheckoutSession' : IDL.Func(
      [ReferenceCode, IDL.Text, IDL.Text],
      [Result_3],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerVisitHistory' : IDL.Func(
      [JobId],
      [IDL.Vec(VisitRecord)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getRequest' : IDL.Func([JobId], [IDL.Opt(JobRequestView)], ['query']),
  'getRequestByReference' : IDL.Func(
      [ReferenceCode],
      [IDL.Opt(JobRequestView)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getVisitHistory' : IDL.Func(
      [ReferenceCode],
      [IDL.Vec(VisitRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listBees' : IDL.Func([], [IDL.Vec(BeeView)], ['query']),
  'listRequests' : IDL.Func([], [IDL.Vec(JobRequestView)], ['query']),
  'recordDeposit' : IDL.Func([ReferenceCode, PaymentMethod], [Result_1], []),
  'scheduleAppointment' : IDL.Func([JobId, Timestamp], [Result_1], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setPackageEnrollment' : IDL.Func([JobId, IDL.Bool], [Result_2], []),
  'setQuote' : IDL.Func([JobId, IDL.Nat, IDL.Text], [Result_1], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitRequest' : IDL.Func([JobRequestInput], [ReferenceCode], []),
  'submitReview' : IDL.Func([ReferenceCode, IDL.Nat, IDL.Text], [Result_1], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBee' : IDL.Func([BeeId, BeeInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ReferenceCode = IDL.Text;
  const JobId = IDL.Nat;
  const JobStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'requested' : IDL.Null,
    'completed' : IDL.Null,
    'quoted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Review = IDL.Record({
    'createdAt' : Timestamp,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const PackageEnrollment = IDL.Record({
    'startedAt' : Timestamp,
    'active' : IDL.Bool,
    'monthlyPrice' : IDL.Nat,
    'includedVisits' : IDL.Nat,
  });
  const Appointment = IDL.Record({
    'confirmed' : IDL.Bool,
    'scheduledAt' : Timestamp,
  });
  const Quote = IDL.Record({
    'discountApplied' : IDL.Bool,
    'discountAmount' : IDL.Nat,
    'note' : IDL.Text,
    'sentAt' : Timestamp,
    'amount' : IDL.Nat,
  });
  const PhotoId = IDL.Text;
  const PaymentMethod = IDL.Variant({
    'stripe' : IDL.Null,
    'cashApp' : IDL.Null,
  });
  const Deposit = IDL.Record({
    'method' : PaymentMethod,
    'paid' : IDL.Bool,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'paidAt' : IDL.Opt(Timestamp),
  });
  const ServiceCategory = IDL.Variant({
    'fixIt' : IDL.Null,
    'showMe' : IDL.Null,
    'house' : IDL.Null,
    'cleanOrganize' : IDL.Null,
    'mowing' : IDL.Null,
    'errands' : IDL.Null,
    'moveLift' : IDL.Null,
    'yardPlants' : IDL.Null,
  });
  const BeeId = IDL.Nat;
  const JobRequestView = IDL.Record({
    'id' : JobId,
    'customerName' : IDL.Text,
    'status' : JobStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'review' : IDL.Opt(Review),
    'packageEnrollment' : IDL.Opt(PackageEnrollment),
    'preferredTiming' : IDL.Text,
    'appointment' : IDL.Opt(Appointment),
    'createdAt' : Timestamp,
    'quote' : IDL.Opt(Quote),
    'description' : IDL.Text,
    'photoIds' : IDL.Vec(PhotoId),
    'deposit' : IDL.Opt(Deposit),
    'ownParts' : IDL.Bool,
    'email' : IDL.Text,
    'referenceCode' : ReferenceCode,
    'category' : ServiceCategory,
    'assignedBeeName' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'assignedBeeId' : IDL.Opt(BeeId),
  });
  const JobError = IDL.Variant({
    'paymentError' : IDL.Text,
    'invalidState' : IDL.Text,
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : JobRequestView, 'err' : JobError });
  const BeeError = IDL.Variant({
    'invalidState' : IDL.Text,
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : JobRequestView, 'err' : BeeError });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BeeInput = IDL.Record({ 'name' : IDL.Text, 'specialty' : IDL.Text });
  const BeeView = IDL.Record({
    'id' : BeeId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'specialty' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : BeeView, 'err' : BeeError });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : JobError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const VisitRecord = IDL.Record({
    'service' : ServiceCategory,
    'completedAt' : Timestamp,
    'jobId' : JobId,
    'referenceCode' : ReferenceCode,
    'beeName' : IDL.Opt(IDL.Text),
    'beeId' : IDL.Opt(BeeId),
  });
  const DashboardStats = IDL.Record({
    'reviewsCount' : IDL.Nat,
    'depositsCollected' : IDL.Nat,
    'newRequests' : IDL.Nat,
    'upcomingAppointments' : IDL.Nat,
    'activeJobs' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const JobRequestInput = IDL.Record({
    'customerName' : IDL.Text,
    'preferredTiming' : IDL.Text,
    'description' : IDL.Text,
    'photoIds' : IDL.Vec(PhotoId),
    'ownParts' : IDL.Bool,
    'email' : IDL.Text,
    'category' : ServiceCategory,
    'phone' : IDL.Text,
    'packageInterest' : IDL.Bool,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_4], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'acceptQuote' : IDL.Func([ReferenceCode], [Result_1], []),
    'advanceStatus' : IDL.Func([JobId], [Result_1], []),
    'assignBeeToJob' : IDL.Func([JobId, BeeId], [Result_2], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmAppointment' : IDL.Func([ReferenceCode], [Result_1], []),
    'confirmDepositPayment' : IDL.Func([ReferenceCode], [Result_1], []),
    'createBee' : IDL.Func([BeeInput], [Result], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDepositCheckoutSession' : IDL.Func(
        [ReferenceCode, IDL.Text, IDL.Text],
        [Result_3],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerVisitHistory' : IDL.Func(
        [JobId],
        [IDL.Vec(VisitRecord)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getRequest' : IDL.Func([JobId], [IDL.Opt(JobRequestView)], ['query']),
    'getRequestByReference' : IDL.Func(
        [ReferenceCode],
        [IDL.Opt(JobRequestView)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getVisitHistory' : IDL.Func(
        [ReferenceCode],
        [IDL.Vec(VisitRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listBees' : IDL.Func([], [IDL.Vec(BeeView)], ['query']),
    'listRequests' : IDL.Func([], [IDL.Vec(JobRequestView)], ['query']),
    'recordDeposit' : IDL.Func([ReferenceCode, PaymentMethod], [Result_1], []),
    'scheduleAppointment' : IDL.Func([JobId, Timestamp], [Result_1], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setPackageEnrollment' : IDL.Func([JobId, IDL.Bool], [Result_2], []),
    'setQuote' : IDL.Func([JobId, IDL.Nat, IDL.Text], [Result_1], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitRequest' : IDL.Func([JobRequestInput], [ReferenceCode], []),
    'submitReview' : IDL.Func(
        [ReferenceCode, IDL.Nat, IDL.Text],
        [Result_1],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBee' : IDL.Func([BeeId, BeeInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };