/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Appointment {
    confirmed: boolean;
    scheduledAt: Timestamp;
}
export type BeeError = {
    __kind__: "invalidState";
    invalidState: string;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notFound";
    notFound: null;
};
export type BeeId = bigint;
export interface BeeInput {
    name: string;
    specialty: string;
}
export interface BeeView {
    id: BeeId;
    name: string;
    createdAt: Timestamp;
    specialty: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface DashboardStats {
    reviewsCount: bigint;
    depositsCollected: bigint;
    newRequests: bigint;
    upcomingAppointments: bigint;
    activeJobs: bigint;
}
export interface Deposit {
    method: PaymentMethod;
    paid: boolean;
    stripeSessionId?: string;
    amount: bigint;
    paidAt?: Timestamp;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface HttpHeader {
    value: string;
    name: string;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export type JobError = {
    __kind__: "paymentError";
    paymentError: string;
} | {
    __kind__: "invalidState";
    invalidState: string;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notFound";
    notFound: null;
};
export type JobId = bigint;
export interface JobRequestInput {
    customerName: string;
    preferredTiming: string;
    description: string;
    photoIds: Array<PhotoId>;
    ownParts: boolean;
    email: string;
    category: ServiceCategory;
    phone: string;
    packageInterest: boolean;
}
export interface JobRequestView {
    id: JobId;
    customerName: string;
    status: JobStatus;
    completedAt?: Timestamp;
    review?: Review;
    packageEnrollment?: PackageEnrollment;
    preferredTiming: string;
    appointment?: Appointment;
    createdAt: Timestamp;
    quote?: Quote;
    description: string;
    photoIds: Array<PhotoId>;
    deposit?: Deposit;
    ownParts: boolean;
    email: string;
    referenceCode: ReferenceCode;
    category: ServiceCategory;
    assignedBeeName?: string;
    phone: string;
    assignedBeeId?: BeeId;
}
export interface PackageEnrollment {
    startedAt: Timestamp;
    active: boolean;
    monthlyPrice: bigint;
    includedVisits: bigint;
}
export type PhotoId = string;
export interface Quote {
    discountApplied: boolean;
    discountAmount: bigint;
    note: string;
    sentAt: Timestamp;
    amount: bigint;
}
export type ReferenceCode = string;
export type Result = {
    __kind__: "ok";
    ok: BeeView;
} | {
    __kind__: "err";
    err: BeeError;
};
export type Result_1 = {
    __kind__: "ok";
    ok: JobRequestView;
} | {
    __kind__: "err";
    err: JobError;
};
export type Result_2 = {
    __kind__: "ok";
    ok: JobRequestView;
} | {
    __kind__: "err";
    err: BeeError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: JobError;
};
export type Result_4 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Review {
    createdAt: Timestamp;
    comment: string;
    rating: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export type Timestamp = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface VisitRecord {
    service: ServiceCategory;
    completedAt: Timestamp;
    jobId: JobId;
    referenceCode: ReferenceCode;
    beeName?: string;
    beeId?: BeeId;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum JobStatus {
    scheduled = "scheduled",
    requested = "requested",
    completed = "completed",
    quoted = "quoted",
    inProgress = "inProgress"
}
export enum PaymentMethod {
    stripe = "stripe",
    cashApp = "cashApp"
}
export enum ServiceCategory {
    fixIt = "fixIt",
    showMe = "showMe",
    house = "house",
    cleanOrganize = "cleanOrganize",
    mowing = "mowing",
    errands = "errands",
    moveLift = "moveLift",
    yardPlants = "yardPlants"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_4>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Guest: accept the quote attached to a job request.
     */
    acceptQuote(referenceCode: ReferenceCode): Promise<Result_1>;
    /**
     * / Admin: advance a job request to its next lifecycle status.
     */
    advanceStatus(id: JobId): Promise<Result_1>;
    /**
     * / Admin: assign a bee to a job request.
     */
    assignBeeToJob(id: JobId, beeId: BeeId): Promise<Result_2>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Guest: confirm the scheduled appointment.
     */
    confirmAppointment(referenceCode: ReferenceCode): Promise<Result_1>;
    /**
     * / Guest: confirm a Stripe deposit payment and mark the deposit paid.
     */
    confirmDepositPayment(referenceCode: ReferenceCode): Promise<Result_1>;
    /**
     * / Admin: create a bee (employee) with a name and specialty.
     */
    createBee(input: BeeInput): Promise<Result>;
    /**
     * / Guest: create a Stripe checkout session for a set of shopping items.
     */
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    /**
     * / Guest: create a Stripe checkout session for the 50% deposit on an accepted quote.
     */
    createDepositCheckoutSession(referenceCode: ReferenceCode, successUrl: string, cancelUrl: string): Promise<Result_3>;
    execute(qJson: string): Promise<Result__1>;
    /**
     * / Return the backend's behavioral API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Admin: read the newest-first visit history for a job request's customer.
     */
    getCustomerVisitHistory(id: JobId): Promise<Array<VisitRecord>>;
    /**
     * / Admin: read dashboard statistics.
     */
    getDashboardStats(): Promise<DashboardStats>;
    /**
     * / Admin: fetch a single job request by id.
     */
    getRequest(id: JobId): Promise<JobRequestView | null>;
    /**
     * / Guest: fetch a job request by its public reference code.
     */
    getRequestByReference(referenceCode: ReferenceCode): Promise<JobRequestView | null>;
    /**
     * / Guest: read the status of a Stripe checkout session.
     */
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    /**
     * / Guest: read the newest-first visit history for a reference code.
     */
    getVisitHistory(referenceCode: ReferenceCode): Promise<Array<VisitRecord>>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Whether Stripe checkout is configured for deposit payments.
     */
    isStripeConfigured(): Promise<boolean>;
    /**
     * / Admin: list all bees.
     */
    listBees(): Promise<Array<BeeView>>;
    /**
     * / Admin: list all job requests.
     */
    listRequests(): Promise<Array<JobRequestView>>;
    /**
     * / Guest: record a deposit payment for an accepted quote.
     */
    recordDeposit(referenceCode: ReferenceCode, method: PaymentMethod): Promise<Result_1>;
    /**
     * / Admin: schedule an appointment for a job request. Notifies BOTH the
     * / customer and the owner.
     */
    scheduleAppointment(id: JobId, scheduledAt: Timestamp): Promise<Result_1>;
    schema(): Promise<string>;
    /**
     * / Admin: mark a job request's customer as being on the monthly package.
     */
    setPackageEnrollment(id: JobId, active: boolean): Promise<Result_2>;
    /**
     * / Admin: set the quote amount and note for a job request. When the customer
     * / indicated they supply their own parts, a 10% discount is applied and
     * / recorded on the quote.
     */
    setQuote(id: JobId, amount: bigint, note: string): Promise<Result_1>;
    /**
     * / Admin: store the Stripe secret key and allowed countries.
     */
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    /**
     * / Guest: submit a new job request and receive its public reference code.
     */
    submitRequest(input: JobRequestInput): Promise<ReferenceCode>;
    /**
     * / Guest: submit a review for a completed job.
     */
    submitReview(referenceCode: ReferenceCode, rating: bigint, comment: string): Promise<Result_1>;
    /**
     * / HTTP outcall transform required by the Stripe client.
     */
    transform(input: TransformationInput): Promise<TransformationOutput>;
    /**
     * / Admin: update a bee's name and specialty.
     */
    updateBee(id: BeeId, input: BeeInput): Promise<Result>;
}
import type { Appointment as _Appointment, BeeError as _BeeError, BeeId as _BeeId, BeeView as _BeeView, Cell as _Cell, Deposit as _Deposit, Error as _Error, JobError as _JobError, JobId as _JobId, JobRequestInput as _JobRequestInput, JobRequestView as _JobRequestView, JobStatus as _JobStatus, PackageEnrollment as _PackageEnrollment, PaymentMethod as _PaymentMethod, PhotoId as _PhotoId, Quote as _Quote, ReferenceCode as _ReferenceCode, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result__1 as _Result__1, Review as _Review, ServiceCategory as _ServiceCategory, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, VisitRecord as _VisitRecord, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_4_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_4_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async acceptQuote(arg0: ReferenceCode): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptQuote(arg0);
                return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptQuote(arg0);
            return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async advanceStatus(arg0: JobId): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.advanceStatus(arg0);
                return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.advanceStatus(arg0);
            return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignBeeToJob(arg0: JobId, arg1: BeeId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.assignBeeToJob(arg0, arg1);
                return from_candid_Result_2_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignBeeToJob(arg0, arg1);
            return from_candid_Result_2_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n35(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n35(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmAppointment(arg0: ReferenceCode): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmAppointment(arg0);
                return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmAppointment(arg0);
            return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmDepositPayment(arg0: ReferenceCode): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmDepositPayment(arg0);
                return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmDepositPayment(arg0);
            return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBee(arg0: BeeInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createBee(arg0);
                return from_candid_Result_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBee(arg0);
            return from_candid_Result_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createDepositCheckoutSession(arg0: ReferenceCode, arg1: string, arg2: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.createDepositCheckoutSession(arg0, arg1, arg2);
                return from_candid_Result_3_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDepositCheckoutSession(arg0, arg1, arg2);
            return from_candid_Result_3_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerVisitHistory(arg0: JobId): Promise<Array<VisitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerVisitHistory(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerVisitHistory(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getRequest(arg0: JobId): Promise<JobRequestView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequest(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequest(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestByReference(arg0: ReferenceCode): Promise<JobRequestView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestByReference(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestByReference(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitHistory(arg0: ReferenceCode): Promise<Array<VisitRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitHistory(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitHistory(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listBees(): Promise<Array<BeeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBees();
            return result;
        }
    }
    async listRequests(): Promise<Array<JobRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRequests();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRequests();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordDeposit(arg0: ReferenceCode, arg1: PaymentMethod): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDeposit(arg0, to_candid_PaymentMethod_n57(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDeposit(arg0, to_candid_PaymentMethod_n57(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async scheduleAppointment(arg0: JobId, arg1: Timestamp): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleAppointment(arg0, arg1);
                return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleAppointment(arg0, arg1);
            return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setPackageEnrollment(arg0: JobId, arg1: boolean): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.setPackageEnrollment(arg0, arg1);
                return from_candid_Result_2_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPackageEnrollment(arg0, arg1);
            return from_candid_Result_2_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async setQuote(arg0: JobId, arg1: bigint, arg2: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.setQuote(arg0, arg1, arg2);
                return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setQuote(arg0, arg1, arg2);
            return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitRequest(arg0: JobRequestInput): Promise<ReferenceCode> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRequest(to_candid_JobRequestInput_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRequest(to_candid_JobRequestInput_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitReview(arg0: ReferenceCode, arg1: bigint, arg2: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2);
                return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2);
            return from_candid_Result_1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBee(arg0: BeeId, arg1: BeeInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBee(arg0, arg1);
                return from_candid_Result_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBee(arg0, arg1);
            return from_candid_Result_n36(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BeeError_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BeeError): BeeError {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Deposit_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deposit): Deposit {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_JobError_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobError): JobError {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_JobRequestView_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobRequestView): JobRequestView {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return "scheduled" in value ? JobStatus.scheduled : "requested" in value ? JobStatus.requested : "completed" in value ? JobStatus.completed : "quoted" in value ? JobStatus.quoted : "inProgress" in value ? JobStatus.inProgress : value;
}
function from_candid_PaymentMethod_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return "stripe" in value ? PaymentMethod.stripe : "cashApp" in value ? PaymentMethod.cashApp : value;
}
function from_candid_Result_1_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return "fixIt" in value ? ServiceCategory.fixIt : "showMe" in value ? ServiceCategory.showMe : "house" in value ? ServiceCategory.house : "cleanOrganize" in value ? ServiceCategory.cleanOrganize : "mowing" in value ? ServiceCategory.mowing : "errands" in value ? ServiceCategory.errands : "moveLift" in value ? ServiceCategory.moveLift : "yardPlants" in value ? ServiceCategory.yardPlants : value;
}
function from_candid_StripeSessionStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_VisitRecord_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisitRecord): VisitRecord {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Review]): Review | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PackageEnrollment]): PackageEnrollment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quote]): Quote | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Deposit]): Deposit | null {
    return value.length === 0 ? null : from_candid_Deposit_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BeeId]): BeeId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobRequestView]): JobRequestView | null {
    return value.length === 0 ? null : from_candid_JobRequestView_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    customerName: string;
    status: _JobStatus;
    completedAt: [] | [_Timestamp];
    review: [] | [_Review];
    packageEnrollment: [] | [_PackageEnrollment];
    preferredTiming: string;
    appointment: [] | [_Appointment];
    createdAt: _Timestamp;
    quote: [] | [_Quote];
    description: string;
    photoIds: Array<_PhotoId>;
    deposit: [] | [_Deposit];
    ownParts: boolean;
    email: string;
    referenceCode: _ReferenceCode;
    category: _ServiceCategory;
    assignedBeeName: [] | [string];
    phone: string;
    assignedBeeId: [] | [_BeeId];
}): {
    id: JobId;
    customerName: string;
    status: JobStatus;
    completedAt?: Timestamp;
    review?: Review;
    packageEnrollment?: PackageEnrollment;
    preferredTiming: string;
    appointment?: Appointment;
    createdAt: Timestamp;
    quote?: Quote;
    description: string;
    photoIds: Array<PhotoId>;
    deposit?: Deposit;
    ownParts: boolean;
    email: string;
    referenceCode: ReferenceCode;
    category: ServiceCategory;
    assignedBeeName?: string;
    phone: string;
    assignedBeeId?: BeeId;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_JobStatus_n16(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.completedAt)),
        review: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.review)),
        packageEnrollment: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.packageEnrollment)),
        preferredTiming: value.preferredTiming,
        appointment: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.appointment)),
        createdAt: value.createdAt,
        quote: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.quote)),
        description: value.description,
        photoIds: value.photoIds,
        deposit: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.deposit)),
        ownParts: value.ownParts,
        email: value.email,
        referenceCode: value.referenceCode,
        category: from_candid_ServiceCategory_n27(_uploadFile, _downloadFile, value.category),
        assignedBeeName: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.assignedBeeName)),
        phone: value.phone,
        assignedBeeId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.assignedBeeId))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: _PaymentMethod;
    paid: boolean;
    stripeSessionId: [] | [string];
    amount: bigint;
    paidAt: [] | [_Timestamp];
}): {
    method: PaymentMethod;
    paid: boolean;
    stripeSessionId?: string;
    amount: bigint;
    paidAt?: Timestamp;
} {
    return {
        method: from_candid_PaymentMethod_n25(_uploadFile, _downloadFile, value.method),
        paid: value.paid,
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.stripeSessionId)),
        amount: value.amount,
        paidAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.paidAt))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n42(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n46(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: _ServiceCategory;
    completedAt: _Timestamp;
    jobId: _JobId;
    referenceCode: _ReferenceCode;
    beeName: [] | [string];
    beeId: [] | [_BeeId];
}): {
    service: ServiceCategory;
    completedAt: Timestamp;
    jobId: JobId;
    referenceCode: ReferenceCode;
    beeName?: string;
    beeId?: BeeId;
} {
    return {
        service: from_candid_ServiceCategory_n27(_uploadFile, _downloadFile, value.service),
        completedAt: value.completedAt,
        jobId: value.jobId,
        referenceCode: value.referenceCode,
        beeName: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.beeName)),
        beeId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.beeId))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _JobRequestView;
} | {
    err: _JobError;
}): {
    __kind__: "ok";
    ok: JobRequestView;
} | {
    __kind__: "err";
    err: JobError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_JobRequestView_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_JobError_n29(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentError: string;
} | {
    invalidState: string;
} | {
    notAuthorized: null;
} | {
    notFound: null;
}): {
    __kind__: "paymentError";
    paymentError: string;
} | {
    __kind__: "invalidState";
    invalidState: string;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "paymentError" in value ? {
        __kind__: "paymentError",
        paymentError: value.paymentError
    } : "invalidState" in value ? {
        __kind__: "invalidState",
        invalidState: value.invalidState
    } : "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _JobRequestView;
} | {
    err: _BeeError;
}): {
    __kind__: "ok";
    ok: JobRequestView;
} | {
    __kind__: "err";
    err: BeeError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_JobRequestView_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_BeeError_n33(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidState: string;
} | {
    notAuthorized: null;
} | {
    notFound: null;
}): {
    __kind__: "invalidState";
    invalidState: string;
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "invalidState" in value ? {
        __kind__: "invalidState",
        invalidState: value.invalidState
    } : "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BeeView;
} | {
    err: _BeeError;
}): {
    __kind__: "ok";
    ok: BeeView;
} | {
    __kind__: "err";
    err: BeeError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_BeeError_n33(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: _JobError;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: JobError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_JobError_n29(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n55(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VisitRecord>): Array<VisitRecord> {
    return value.map((x)=>from_candid_VisitRecord_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobRequestView>): Array<JobRequestView> {
    return value.map((x)=>from_candid_JobRequestView_n14(_uploadFile, _downloadFile, x));
}
function to_candid_JobRequestInput_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobRequestInput): _JobRequestInput {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return value == PaymentMethod.stripe ? {
        stripe: null
    } : value == PaymentMethod.cashApp ? {
        cashApp: null
    } : value;
}
function to_candid_ServiceCategory_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return value == ServiceCategory.fixIt ? {
        fixIt: null
    } : value == ServiceCategory.showMe ? {
        showMe: null
    } : value == ServiceCategory.house ? {
        house: null
    } : value == ServiceCategory.cleanOrganize ? {
        cleanOrganize: null
    } : value == ServiceCategory.mowing ? {
        mowing: null
    } : value == ServiceCategory.errands ? {
        errands: null
    } : value == ServiceCategory.moveLift ? {
        moveLift: null
    } : value == ServiceCategory.yardPlants ? {
        yardPlants: null
    } : value;
}
function to_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    preferredTiming: string;
    description: string;
    photoIds: Array<PhotoId>;
    ownParts: boolean;
    email: string;
    category: ServiceCategory;
    phone: string;
    packageInterest: boolean;
}): {
    customerName: string;
    preferredTiming: string;
    description: string;
    photoIds: Array<_PhotoId>;
    ownParts: boolean;
    email: string;
    category: _ServiceCategory;
    phone: string;
    packageInterest: boolean;
} {
    return {
        customerName: value.customerName,
        preferredTiming: value.preferredTiming,
        description: value.description,
        photoIds: value.photoIds,
        ownParts: value.ownParts,
        email: value.email,
        category: to_candid_ServiceCategory_n60(_uploadFile, _downloadFile, value.category),
        phone: value.phone,
        packageInterest: value.packageInterest
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
